apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: service-polyglot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-polyglot
  template:
    metadata:
      labels:
        app: service-polyglot
    spec:
      containers:
      - name: service-polyglot
        image: antony0618/ms-account:latest
        ports:
        - containerPort: 80 #change port value 8080 on microservice development
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: service-polyglot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # same to line 21
    name: http
